spring.application.name=placement-portal-backend
spring.data.mongodb.uri=mongodb://localhost:27017/placementportal
spring.data.mongodb.database=placementportal
logging.level.org.springframework.boot.context.config=DEBUG
debug=true